# Site settings
title:       Benjamin Schachter's Blog
email:       benschac@gmail.com
author:      Benjamin Schachter
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "http://benschac.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Social icons
show_social_icons: true
github_username: benschac
twitter_username: benschac
google_plus_id: benschac
linkedin_username: benjaminschachter
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
